/**
 * User_API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Users } from './users';

export interface Posts { 
    id?: number;
    title?: string;
    userId?: number;
    creatDate?: Date;
    createBy?: number;
    userss?: Users;
}